package com.atguigu.java.ai.langchain4j.controller;

import com.atguigu.java.ai.langchain4j.entity.AutoExamConfig;
import com.atguigu.java.ai.langchain4j.entity.AutoGeneratedExam;
import com.atguigu.java.ai.langchain4j.entity.PageResponse;
import com.atguigu.java.ai.langchain4j.entity.Result;
import com.atguigu.java.ai.langchain4j.entity.dto.ExamGenerationRequest;
import com.atguigu.java.ai.langchain4j.entity.dto.ExamPreviewVO;
import com.atguigu.java.ai.langchain4j.service.AutoExamService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

/**
 * 自动组卷控制器
 */
@Slf4j
@RestController
@RequestMapping("/auto-exam")
@Tag(name = "自动组卷", description = "基于AI的智能组卷功能")
public class AutoExamController {
    
    @Autowired
    private AutoExamService autoExamService;
    
    /**
     * 创建组卷配置
     */
    @PostMapping("/config")
    @Operation(summary = "创建组卷配置", description = "创建新的自动组卷配置")
    public Result<AutoExamConfig> createConfig(@RequestBody ExamGenerationRequest request) {
        log.info("创建组卷配置请求: {}", request);
        return autoExamService.createConfig(request);
    }
    
    /**
     * 智能组卷
     */
    @PostMapping("/generate")
    @Operation(summary = "智能组卷", description = "基于配置智能生成试卷")
    public Result<AutoGeneratedExam> generateExam(@RequestBody ExamGenerationRequest request) {
        log.info("智能组卷请求: {}", request);
        return autoExamService.generateExam(request);
    }
    
    /**
     * 预览试卷
     */
    @GetMapping("/preview/{examId}")
    @Operation(summary = "预览试卷", description = "预览生成的试卷内容")
    public Result<ExamPreviewVO> previewExam(@PathVariable("examId") Long examId) {
        log.info("预览试卷请求: examId={}", examId);
        return autoExamService.previewExam(examId);
    }
    
    /**
     * 调整试卷
     */
    @PostMapping("/adjust/{examId}")
    @Operation(summary = "调整试卷", description = "智能调整试卷内容")
    public Result<AutoGeneratedExam> adjustExam(
            @PathVariable("examId") Long examId,
            @RequestParam("adjustmentType") String adjustmentType,
            @RequestParam("requirements") String requirements) {
        log.info("调整试卷请求: examId={}, type={}, requirements={}", examId, adjustmentType, requirements);
        return autoExamService.adjustExam(examId, adjustmentType, requirements);
    }
    
    /**
     * 发布试卷
     */
    @PostMapping("/save")
    @Operation(summary = "保存试卷", description = "将预览的试卷保存到数据库")
    public Result<Long> saveExam(@RequestBody AutoGeneratedExam examPreview) {
        log.info("保存试卷请求: title={}", examPreview.getExamTitle());
        return autoExamService.saveExam(examPreview);
    }
    
    @PostMapping("/publish/{examId}")
    @Operation(summary = "发布试卷", description = "发布试卷供学生使用")
    public Result<String> publishExam(@PathVariable("examId") Long examId, @RequestParam("teacherId") Long teacherId) {
        log.info("发布试卷请求: examId={}, teacherId={}", examId, teacherId);
        return autoExamService.publishExam(examId, teacherId);
    }
    
    @PostMapping("/publish-direct")
    @Operation(summary = "直接发布试卷", description = "直接发布预览中的试卷数据")
    public Result<String> publishExamDirect(@RequestBody AutoGeneratedExam examData, 
                                          @RequestParam("teacherId") Long teacherId,
                                          @RequestParam(value = "deadline", required = false) String deadline) {
        log.info("直接发布试卷请求: title={}, teacherId={}, deadline={}", examData.getExamTitle(), teacherId, deadline);
        return autoExamService.publishExamDirect(examData, teacherId, deadline);
    }
    
    /**
     * 获取组卷历史
     */
    @GetMapping("/history")
    @Operation(summary = "获取组卷历史", description = "获取教师的组卷历史记录")
    public Result<PageResponse<AutoGeneratedExam>> getGenerationHistory(
            @RequestParam("teacherId") Long teacherId,
            @RequestParam(value = "page", defaultValue = "1") int page,
            @RequestParam(value = "pageSize", defaultValue = "10") int pageSize) {
        log.info("获取组卷历史请求: teacherId={}, page={}, pageSize={}", teacherId, page, pageSize);
        return autoExamService.getGenerationHistory(teacherId, page, pageSize);
    }
    
    /**
     * 获取配置列表
     */
    @GetMapping("/configs")
    @Operation(summary = "获取配置列表", description = "获取课程的组卷配置列表")
    public Result<List<AutoExamConfig>> getConfigList(
            @RequestParam("courseId") Long courseId,
            @RequestParam("teacherId") Long teacherId) {
        log.info("获取配置列表请求: courseId={}, teacherId={}", courseId, teacherId);
        return autoExamService.getConfigList(courseId, teacherId);
    }
    
    /**
     * 删除配置
     */
    @DeleteMapping("/config/{configId}")
    @Operation(summary = "删除配置", description = "删除组卷配置")
    public Result<String> deleteConfig(@PathVariable("configId") Long configId) {
        log.info("删除配置请求: configId={}", configId);
        return autoExamService.deleteConfig(configId);
    }
    
    /**
     * 更新配置
     */
    @PutMapping("/config/{configId}")
    @Operation(summary = "更新配置", description = "更新组卷配置")
    public Result<AutoExamConfig> updateConfig(
            @PathVariable("configId") Long configId,
            @RequestBody ExamGenerationRequest request) {
        log.info("更新配置请求: configId={}, request={}", configId, request);
        return autoExamService.updateConfig(configId, request);
    }
    
    /**
     * 快速组卷（使用默认配置）
     */
    @PostMapping("/quick-generate")
    @Operation(summary = "快速组卷", description = "使用默认配置快速生成试卷")
    public Result<AutoGeneratedExam> quickGenerateExam(
            @RequestParam("courseId") Long courseId,
            @RequestParam("teacherId") Long teacherId,
            @RequestParam("examTitle") String examTitle,
            @RequestParam(value = "totalQuestions", defaultValue = "20") Integer totalQuestions) {
        log.info("快速组卷请求: courseId={}, teacherId={}, title={}, totalQuestions={}", 
                courseId, teacherId, examTitle, totalQuestions);
        
        // 构建默认配置
        ExamGenerationRequest request = new ExamGenerationRequest();
        request.setCourseId(courseId);
        request.setTeacherId(teacherId);
        request.setExamTitle(examTitle);
        request.setTotalQuestions(totalQuestions);
        
        // 设置默认题型分布
        request.setQuestionDistribution(Map.of(
            "choice", totalQuestions * 6 / 10,  // 60%选择题
            "short_answer", totalQuestions * 3 / 10,  // 30%简答题
            "programming", totalQuestions * 1 / 10   // 10%编程题
        ));
        
        // 设置默认难度分布
        request.setDifficultyDistribution(Map.of(
            "easy", 0.2,
            "medium", 0.5,
            "hard", 0.3
        ));
        
        // 设置默认时间限制
        request.setTimeLimitMinutes(totalQuestions * 5); // 每题5分钟
        
        return autoExamService.generateExam(request);
    }
    
    /**
     * 获取试卷统计信息
     */
    @GetMapping("/stats/{courseId}")
    @Operation(summary = "获取试卷统计", description = "获取课程的试卷统计信息")
    public Result<Object> getExamStats(@PathVariable Long courseId) {
        log.info("获取试卷统计请求: courseId={}", courseId);
        
        // 这里可以实现统计逻辑
        // 比如：总试卷数、平均质量评分、题型分布等
        
        return Result.ok(Map.of(
            "totalExams", 0,
            "averageQuality", 0.0,
            "questionTypeDistribution", Map.of(
                "choice", 0,
                "short_answer", 0,
                "programming", 0
            )
        ));
    }
}
