package com.atguigu.java.ai.langchain4j.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * 自动生成试卷实体
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("auto_generated_exam")
public class AutoGeneratedExam {
    
    @TableId(value = "id", type = IdType.AUTO)
    private Long id;
    
    private Long configId;
    
    private String examTitle;
    
    private String examDescription;
    
    private String generationStrategy;
    
    private String aiModelUsed;
    
    private String generationPrompt;
    
    private String generationMetadata; // JSON格式存储生成元数据
    
    private BigDecimal qualityScore;
    
    private String status; // draft, generated, reviewed, published, archived
    
    private LocalDateTime createdAt;
    
    private LocalDateTime reviewedAt;
    
    private LocalDateTime publishedAt;
    
    private Long createdBy;
    
    // 临时字段，用于预览阶段存储题目选择结果，不映射到数据库
    @TableField(exist = false)
    private List<QuestionSelection> questionSelection;
}
