package com.atguigu.java.ai.langchain4j.service;

import com.atguigu.java.ai.langchain4j.entity.AutoExamConfig;
import com.atguigu.java.ai.langchain4j.entity.AutoGeneratedExam;
import com.atguigu.java.ai.langchain4j.entity.dto.ExamGenerationRequest;
import com.atguigu.java.ai.langchain4j.entity.dto.ExamPreviewVO;
import com.atguigu.java.ai.langchain4j.entity.Result;
import com.atguigu.java.ai.langchain4j.entity.PageResponse;

import java.util.List;

/**
 * 自动组卷服务接口
 */
public interface AutoExamService {
    
    /**
     * 创建组卷配置
     */
    Result<AutoExamConfig> createConfig(ExamGenerationRequest request);
    
    /**
     * 智能组卷
     */
    Result<AutoGeneratedExam> generateExam(ExamGenerationRequest request);
    
    /**
     * 预览试卷
     */
    Result<ExamPreviewVO> previewExam(Long examId);
    
    /**
     * 调整试卷
     */
    Result<AutoGeneratedExam> adjustExam(Long examId, String adjustmentType, String requirements);
    
    /**
     * 保存试卷（从预览状态保存到数据库）
     */
    Result<Long> saveExam(AutoGeneratedExam examPreview);
    
    /**
     * 发布试卷
     */
    Result<String> publishExam(Long examId, Long teacherId);
    
    /**
     * 直接发布试卷
     */
    Result<String> publishExamDirect(AutoGeneratedExam examData, Long teacherId, String deadline);
    
    /**
     * 获取组卷历史
     */
    Result<PageResponse<AutoGeneratedExam>> getGenerationHistory(Long teacherId, int page, int pageSize);
    
    /**
     * 获取配置列表
     */
    Result<List<AutoExamConfig>> getConfigList(Long courseId, Long teacherId);
    
    /**
     * 删除配置
     */
    Result<String> deleteConfig(Long configId);
    
    /**
     * 更新配置
     */
    Result<AutoExamConfig> updateConfig(Long configId, ExamGenerationRequest request);
}
