package com.atguigu.java.ai.langchain4j.mapper;

import com.atguigu.java.ai.langchain4j.entity.AutoGeneratedExam;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * 自动生成试卷Mapper
 */
@Mapper
public interface AutoGeneratedExamMapper extends BaseMapper<AutoGeneratedExam> {
    
    /**
     * 根据配置ID查询试卷列表
     */
    List<AutoGeneratedExam> selectByConfigId(@Param("configId") Long configId);
    
    /**
     * 根据教师ID查询试卷列表
     */
    List<AutoGeneratedExam> selectByTeacherId(@Param("teacherId") Long teacherId);
    
    /**
     * 根据状态查询试卷列表
     */
    List<AutoGeneratedExam> selectByStatus(@Param("status") String status);
}
