package com.atguigu.java.ai.langchain4j.service.Impl;

import com.atguigu.java.ai.langchain4j.assistant.AutoExamAgent;
import com.atguigu.java.ai.langchain4j.entity.*;
import com.atguigu.java.ai.langchain4j.entity.dto.ExamGenerationRequest;
import com.atguigu.java.ai.langchain4j.entity.dto.ExamPreviewVO;
import com.atguigu.java.ai.langchain4j.mapper.*;
import com.atguigu.java.ai.langchain4j.service.AutoExamService;
import com.atguigu.java.ai.langchain4j.service.CourseService;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 自动组卷服务实现
 */
@Slf4j
@Service
public class AutoExamServiceImpl implements AutoExamService {
    
    @Autowired
    private AutoExamAgent autoExamAgent;
    
    @Autowired
    private AutoExamConfigMapper autoExamConfigMapper;
    
    @Autowired
    private AutoGeneratedExamMapper autoGeneratedExamMapper;
    
    @Autowired
    private AutoExamQuestionMapper autoExamQuestionMapper;
    
    @Autowired
    private QuestionBankMapper questionBankMapper;

    @Autowired
    private com.atguigu.java.ai.langchain4j.mapper.ExamMapper examMapper;
    
    @Autowired
    private com.atguigu.java.ai.langchain4j.mapper.ExamQuestionMapper examQuestionMapper;
    
    @Autowired
    private KnowledgePointMapper knowledgePointMapper;
    
    @Autowired
    private CourseService courseService;
    
    private final ObjectMapper objectMapper = new ObjectMapper();
    
    @Override
    @Transactional
    public Result<AutoExamConfig> createConfig(ExamGenerationRequest request) {
        try {
            AutoExamConfig config = new AutoExamConfig();
            config.setCourseId(request.getCourseId());
            config.setTeacherId(request.getTeacherId());
            config.setConfigName(request.getExamTitle() + "_配置");
            config.setTotalQuestions(request.getTotalQuestions());
            config.setQuestionDistribution(objectMapper.writeValueAsString(request.getQuestionDistribution()));
            config.setDifficultyDistribution(objectMapper.writeValueAsString(request.getDifficultyDistribution()));
            config.setKnowledgePointWeights(objectMapper.writeValueAsString(request.getKnowledgePointWeights()));
            config.setTimeLimitMinutes(request.getTimeLimitMinutes());
            config.setAiPromptTemplate(request.getAiPromptTemplate());
            config.setIsActive(true);
            config.setCreatedAt(LocalDateTime.now());
            
            autoExamConfigMapper.insert(config);
            return Result.ok(config);
        } catch (Exception e) {
            log.error("创建组卷配置失败", e);
            return Result.error("创建组卷配置失败: " + e.getMessage());
        }
    }
    
    @Override
    @Transactional
    public Result<AutoGeneratedExam> generateExam(ExamGenerationRequest request) {
        try {
            long startTime = System.currentTimeMillis();
            
            // 1. 获取课程信息
            Course course = courseService.getCourseById(request.getCourseId());
            if (course == null) {
                return Result.error("课程不存在");
            }
            
            // 2. 获取知识点信息
            List<KnowledgePoint> knowledgePoints = knowledgePointMapper.selectByCourseId(request.getCourseId());
            
            // 3. 获取题库统计信息
            QuestionBankStats stats = getQuestionBankStats(request.getCourseId());
            
            // 4. 根据选中的知识点和题库分类从题库中筛选题目
            List<QuestionBank> availableQuestions = getQuestionsByKnowledgePoints(
                request.getCourseId(), 
                request.getSelectedKnowledgePoints(),
                request.getCategoryId()
            );
            
            if (availableQuestions.isEmpty()) {
                return Result.error("所选知识点下没有可用题目，请选择其他知识点或添加题目到题库");
            }
            
            // 5. 先按难度占比从题库中抽题（硬性兜底），不足则用其他难度补足
            List<Long> preSelected = enforceDifficultySampling(
                availableQuestions,
                request.getTotalQuestions(),
                request.getDifficultyDistribution()
            );

            // 6. 始终使用筛选出的题目进行组卷
            String aiResponse = autoExamAgent.generateExamFromQuestionBank(
                    request.getCourseId(),
                    course.getCourseName(),
                request.getSelectedKnowledgePoints() != null && !request.getSelectedKnowledgePoints().isEmpty() 
                    ? String.join(", ", request.getSelectedKnowledgePoints())
                    : "所有知识点",
                    request.getExamTitle(),
                    request.getExamDescription(),
                    request.getTotalQuestions(),
                    objectMapper.writeValueAsString(request.getQuestionDistribution()),
                    objectMapper.writeValueAsString(request.getDifficultyDistribution()),
                    request.getTimeLimitMinutes(),
                    request.getGenerationStrategy(),
                    buildQuestionBankJson(availableQuestions)
                );
            
            // 7. 解析AI响应
            ExamGenerationResult result = parseAIResponse(aiResponse);
            
            // 如果AI未返回题目或难度覆盖不符合预期，则用预选题构建一个保底的选择
            if (result.getQuestionSelection() == null || result.getQuestionSelection().isEmpty()) {
                List<QuestionSelection> fallback = preSelected.stream().map(qid -> {
                    QuestionBank qb = questionBankMapper.selectById(qid);
                    QuestionSelection s = new QuestionSelection();
                    s.setQuestionId(qid);
                    s.setDifficulty(mapDifficultyToInt(qb != null ? qb.getDifficultyLevel() : null));
                    s.setEstimatedTime( qb != null && qb.getEstimatedTimeMinutes()!=null ? qb.getEstimatedTimeMinutes() : 5);
                    s.setKnowledgePoint(qb != null ? qb.getKnowledgePoint() : null);
                    s.setReason("按难度占比预选");
                    return s;
                }).collect(Collectors.toList());
                result.setQuestionSelection(fallback);
            }
            // 若AI返回但难度严重偏离目标，也强制重平衡
            else {
                List<QuestionSelection> rebalanced = validateAndRebalanceSelection(availableQuestions, result.getQuestionSelection(),
                        request.getTotalQuestions(), normalizeDifficultyDistribution(request.getDifficultyDistribution()));
                if (rebalanced != null) {
                    result.setQuestionSelection(rebalanced);
                }
            }

            // 8. 创建试卷记录（仅预览，不保存到数据库）
            AutoGeneratedExam exam = createExamRecord(request, result);
            
            // 9. 将题目选择结果附加到试卷对象中，供前端预览
            exam.setQuestionSelection(result.getQuestionSelection());
            
            // 10. 记录生成日志（仅记录，不保存）
            logGeneration(request, aiResponse, result, System.currentTimeMillis() - startTime);
            
            return Result.ok(exam);
        } catch (Exception e) {
            log.error("智能组卷失败", e);
            return Result.error("智能组卷失败: " + e.getMessage());
        }
    }
    
    @Override
    public Result<ExamPreviewVO> previewExam(Long examId) {
        try {
            log.info("开始预览试卷: examId={}", examId);
            
            AutoGeneratedExam exam = autoGeneratedExamMapper.selectById(examId);
            if (exam == null) {
                log.warn("试卷不存在: examId={}", examId);
                return Result.error("试卷不存在");
            }
            
            log.info("找到试卷: examId={}, title={}", examId, exam.getExamTitle());
            
            // 获取试卷题目
            List<AutoExamQuestion> examQuestions = autoExamQuestionMapper.selectByExamId(examId);
            log.info("查询到试卷题目数量: examId={}, count={}", examId, examQuestions.size());
            
            if (examQuestions.isEmpty()) {
                log.warn("试卷题目为空: examId={}", examId);
            } else {
                for (AutoExamQuestion eq : examQuestions) {
                    log.info("试卷题目: examId={}, questionBankId={}, order={}", 
                        eq.getExamId(), eq.getQuestionBankId(), eq.getQuestionOrder());
                }
            }
            
            // 构建预览VO
            ExamPreviewVO preview = buildExamPreviewVO(exam, examQuestions);
            
            log.info("构建预览VO完成: examId={}, totalQuestions={}", examId, preview.getTotalQuestions());
            
            return Result.ok(preview);
        } catch (Exception e) {
            log.error("预览试卷失败", e);
            return Result.error("预览试卷失败: " + e.getMessage());
        }
    }
    
    @Override
    @Transactional
    public Result<AutoGeneratedExam> adjustExam(Long examId, String adjustmentType, String requirements) {
        try {
            AutoGeneratedExam exam = autoGeneratedExamMapper.selectById(examId);
            if (exam == null) {
                return Result.error("试卷不存在");
            }
            
            // 直接处理简单调整（remove/replace/add），避免AI响应markdown导致解析失败
            if ("remove".equalsIgnoreCase(adjustmentType)) {
                Long qid = extractQuestionId(requirements);
                if (qid == null) {
                    return Result.error("缺少questionId，无法删除");
                }
                autoExamQuestionMapper.deleteByExamAndQuestion(examId, qid);
                reorderExamQuestions(examId);
                return Result.ok(exam);
            }
            
            // 获取当前题目
            List<AutoExamQuestion> currentQuestions = autoExamQuestionMapper.selectByExamId(examId);
            
            // 获取可选题目（此处示例用courseId，生产应根据需求过滤）
            List<QuestionBank> availableQuestions = questionBankMapper.selectList(new QueryWrapper<>());
            
            // 调用AI调整
            String aiResponse = autoExamAgent.adjustExam(
                examId,
                buildCurrentQuestionsJson(currentQuestions),
                adjustmentType,
                requirements,
                buildAvailableQuestionsJson(availableQuestions)
            );
            
            // 解析调整建议并应用（parseAdjustmentResponse内部已处理markdown代码块）
            ExamAdjustmentResult adjustmentResult = parseAdjustmentResponse(aiResponse);
            applyAdjustment(examId, adjustmentResult);
            
            return Result.ok(exam);
        } catch (Exception e) {
            log.error("调整试卷失败", e);
            return Result.error("调整试卷失败: " + e.getMessage());
        }
    }
    
    /**
     * 保存试卷（从预览状态保存到数据库）
     */
    @Transactional
    public Result<Long> saveExam(AutoGeneratedExam examPreview) {
        try {
            // 保存试卷记录
            examPreview.setStatus("generated");
            examPreview.setCreatedAt(LocalDateTime.now());
            autoGeneratedExamMapper.insert(examPreview);
            
            // 保存试卷题目关联
            if (examPreview.getQuestionSelection() != null && !examPreview.getQuestionSelection().isEmpty()) {
                saveExamQuestions(examPreview.getId(), examPreview.getQuestionSelection());
            }
            
            return Result.ok(examPreview.getId());
        } catch (Exception e) {
            log.error("保存试卷失败", e);
            return Result.error("保存试卷失败: " + e.getMessage());
        }
    }
    
    @Override
    @Transactional
    public Result<String> publishExam(Long examId, Long teacherId) {
        try {
            AutoGeneratedExam exam = autoGeneratedExamMapper.selectById(examId);
            if (exam == null) {
                return Result.error("试卷不存在");
            }
            
            exam.setStatus("published");
            exam.setPublishedAt(LocalDateTime.now());
            autoGeneratedExamMapper.updateById(exam);

            // 同步创建正式考试记录，供"考试总览"展示
            Long courseId = null;
            List<AutoExamQuestion> eqs = autoExamQuestionMapper.selectByExamId(examId);
            if (!eqs.isEmpty()) {
                QuestionBank qb = questionBankMapper.selectById(eqs.get(0).getQuestionBankId());
                if (qb != null) courseId = qb.getCourseId();
            }
            com.atguigu.java.ai.langchain4j.entity.Exam formal = new com.atguigu.java.ai.langchain4j.entity.Exam();
            formal.setCourseId(courseId);
            formal.setTeacherId(teacherId); // 使用传入的teacherId而不是exam.getCreatedBy()
            formal.setTitle(exam.getExamTitle());
            formal.setDescription(exam.getExamDescription());
            formal.setExamDate(LocalDate.now());
            formal.setDurationMinutes(120);
            formal.setCreatedAt(LocalDateTime.now());
            examMapper.insert(formal);
            
            // 同步创建exam_question关联记录，供学生端查询
            Long formalExamId = formal.getId();
            for (AutoExamQuestion aeq : eqs) {
                // 插入到exam_question表
                examQuestionMapper.insertExamQuestion(formalExamId, aeq.getQuestionBankId());
            }
            
            return Result.ok();
        } catch (Exception e) {
            log.error("发布试卷失败", e);
            return Result.error("发布试卷失败: " + e.getMessage());
        }
    }
    
    @Override
    @Transactional
    public Result<String> publishExamDirect(AutoGeneratedExam examData, Long teacherId, String deadline) {
        try {
            // 1. 先保存试卷到auto_generated_exam表
            examData.setStatus("published");
            examData.setCreatedAt(LocalDateTime.now());
            examData.setPublishedAt(LocalDateTime.now());
            examData.setCreatedBy(teacherId);
            autoGeneratedExamMapper.insert(examData);
            
            // 2. 保存题目关联到auto_exam_question表
            if (examData.getQuestionSelection() != null && !examData.getQuestionSelection().isEmpty()) {
                saveExamQuestions(examData.getId(), examData.getQuestionSelection());
            }
            
            // 3. 创建正式考试记录，供"考试总览"展示
            Long courseId = null;
            if (examData.getQuestionSelection() != null && !examData.getQuestionSelection().isEmpty()) {
                QuestionBank qb = questionBankMapper.selectById(examData.getQuestionSelection().get(0).getQuestionId());
                if (qb != null) courseId = qb.getCourseId();
            }
            
            com.atguigu.java.ai.langchain4j.entity.Exam formal = new com.atguigu.java.ai.langchain4j.entity.Exam();
            formal.setCourseId(courseId);
            formal.setTeacherId(teacherId);
            formal.setTitle(examData.getExamTitle());
            formal.setDescription(examData.getExamDescription());
            // 使用前端传递的截止日期，如果没有则使用当前日期
            if (deadline != null && !deadline.trim().isEmpty()) {
                try {
                    // 解析截止日期字符串，格式为 "YYYY-MM-DD HH:mm:ss"
                    LocalDateTime deadlineDateTime = LocalDateTime.parse(deadline, 
                        java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                    formal.setExamDate(deadlineDateTime.toLocalDate());
                } catch (Exception e) {
                    log.warn("解析截止日期失败，使用当前日期: {}", deadline, e);
                    formal.setExamDate(LocalDate.now());
                }
            } else {
                formal.setExamDate(LocalDate.now());
            }
            formal.setDurationMinutes(120); // 默认120分钟
            formal.setCreatedAt(LocalDateTime.now());
            examMapper.insert(formal);
            
            // 4. 同步创建exam_question关联记录，供学生端查询
            Long formalExamId = formal.getId();
            if (examData.getQuestionSelection() != null) {
                for (QuestionSelection qs : examData.getQuestionSelection()) {
                    examQuestionMapper.insertExamQuestion(formalExamId, qs.getQuestionId());
                }
            }
            
            return Result.ok("发布成功");
        } catch (Exception e) {
            log.error("直接发布试卷失败", e);
            return Result.error("发布试卷失败: " + e.getMessage());
        }
    }
    
    @Override
    public Result<PageResponse<AutoGeneratedExam>> getGenerationHistory(Long teacherId, int page, int pageSize) {
        try {
            Page<AutoGeneratedExam> pageParam = new Page<>(page, pageSize);
            QueryWrapper<AutoGeneratedExam> queryWrapper = new QueryWrapper<>();
            queryWrapper.eq("created_by", teacherId)
                       .orderByDesc("created_at");
            
            Page<AutoGeneratedExam> result = autoGeneratedExamMapper.selectPage(pageParam, queryWrapper);
            
            PageResponse<AutoGeneratedExam> pageResponse = new PageResponse<>();
            pageResponse.setRecords(result.getRecords());
            pageResponse.setTotal(result.getTotal());
            pageResponse.setPage((int) result.getCurrent());
            pageResponse.setPageSize((int) result.getSize());
            
            return Result.ok(pageResponse);
        } catch (Exception e) {
            log.error("获取组卷历史失败", e);
            return Result.error("获取组卷历史失败: " + e.getMessage());
        }
    }
    
    @Override
    public Result<List<AutoExamConfig>> getConfigList(Long courseId, Long teacherId) {
        try {
            List<AutoExamConfig> configs = autoExamConfigMapper.selectByCourseAndTeacher(courseId, teacherId);
            return Result.ok(configs);
        } catch (Exception e) {
            log.error("获取配置列表失败", e);
            return Result.error("获取配置列表失败: " + e.getMessage());
        }
    }
    
    @Override
    @Transactional
    public Result<String> deleteConfig(Long configId) {
        try {
            autoExamConfigMapper.deleteById(configId);
            return Result.ok();
        } catch (Exception e) {
            log.error("删除配置失败", e);
            return Result.error("删除配置失败: " + e.getMessage());
        }
    }
    
    @Override
    @Transactional
    public Result<AutoExamConfig> updateConfig(Long configId, ExamGenerationRequest request) {
        try {
            AutoExamConfig config = autoExamConfigMapper.selectById(configId);
            if (config == null) {
                return Result.error("配置不存在");
            }
            
            config.setConfigName(request.getExamTitle() + "_配置");
            config.setTotalQuestions(request.getTotalQuestions());
            config.setQuestionDistribution(objectMapper.writeValueAsString(request.getQuestionDistribution()));
            config.setDifficultyDistribution(objectMapper.writeValueAsString(request.getDifficultyDistribution()));
            config.setKnowledgePointWeights(objectMapper.writeValueAsString(request.getKnowledgePointWeights()));
            config.setTimeLimitMinutes(request.getTimeLimitMinutes());
            config.setAiPromptTemplate(request.getAiPromptTemplate());
            config.setUpdatedAt(LocalDateTime.now());
            
            autoExamConfigMapper.updateById(config);
            return Result.ok(config);
        } catch (Exception e) {
            log.error("更新配置失败", e);
            return Result.error("更新配置失败: " + e.getMessage());
        }
    }
    
    // 私有辅助方法
    private QuestionBankStats getQuestionBankStats(Long courseId) {
        // 实现题库统计逻辑
        return new QuestionBankStats();
    }
    
    private String buildKnowledgePointsJson(List<KnowledgePoint> knowledgePoints) {
        // 构建知识点JSON字符串
        return knowledgePoints.stream()
                .map(kp -> String.format("{\"id\":%d,\"title\":\"%s\"}", 
                    kp.getId(), kp.getTitle()))
                .collect(Collectors.joining(","));
    }
    
    private ExamGenerationResult parseAIResponse(String aiResponse) {
        // 解析AI响应
        try {
            // 处理AI响应可能包含的markdown代码块
            String jsonResponse = aiResponse.trim();
            
            // 如果响应被包装在markdown代码块中，提取JSON部分
            if (jsonResponse.startsWith("```json")) {
                int startIndex = jsonResponse.indexOf("```json") + 7;
                int endIndex = jsonResponse.lastIndexOf("```");
                if (endIndex > startIndex) {
                    jsonResponse = jsonResponse.substring(startIndex, endIndex).trim();
                }
            } else if (jsonResponse.startsWith("```")) {
                int startIndex = jsonResponse.indexOf("```") + 3;
                int endIndex = jsonResponse.lastIndexOf("```");
                if (endIndex > startIndex) {
                    jsonResponse = jsonResponse.substring(startIndex, endIndex).trim();
                }
            }
            
            log.info("解析的JSON响应: {}", jsonResponse);
            
            ExamGenerationResult result = objectMapper.readValue(jsonResponse, ExamGenerationResult.class);
            
            // 处理suggestions字段，统一转换为List<String>格式
            if (result.getSuggestions() != null) {
                List<String> suggestionsList = new ArrayList<>();
                if (result.getSuggestions() instanceof String) {
                    // 如果是字符串，直接添加
                    suggestionsList.add((String) result.getSuggestions());
                } else if (result.getSuggestions() instanceof List) {
                    // 如果是列表，转换每个元素为字符串
                    @SuppressWarnings("unchecked")
                    List<Object> suggestionsObj = (List<Object>) result.getSuggestions();
                    for (Object suggestion : suggestionsObj) {
                        suggestionsList.add(suggestion.toString());
                    }
                }
                // 将处理后的列表重新设置
                result.setSuggestions(suggestionsList);
            }
            
            return result;
        } catch (Exception e) {
            log.error("解析AI响应失败，原始响应: {}", aiResponse, e);
            throw new RuntimeException("解析AI响应失败", e);
        }
    }
    
    private AutoGeneratedExam createExamRecord(ExamGenerationRequest request, ExamGenerationResult result) {
        AutoGeneratedExam exam = new AutoGeneratedExam();
        exam.setConfigId(1L); // 这里应该从配置中获取
        exam.setExamTitle(request.getExamTitle());
        exam.setExamDescription(request.getExamDescription());
        exam.setGenerationStrategy("AI智能组卷");
        exam.setAiModelUsed("qwen-plus");
        exam.setStatus("generated");
        exam.setCreatedBy(request.getTeacherId());
        exam.setCreatedAt(LocalDateTime.now());
        return exam;
    }
    
    private void saveExamQuestions(Long examId, List<QuestionSelection> questionSelections) {
        // 保存试卷题目关联
        List<AutoExamQuestion> examQuestions = new ArrayList<>();
        
        // 去重处理：使用Set来跟踪已添加的题目ID
        Set<Long> addedQuestionIds = new HashSet<>();
        int order = 1;
        
        for (QuestionSelection selection : questionSelections) {
            // 如果题目ID已经存在，跳过重复的题目
            if (addedQuestionIds.contains(selection.getQuestionId())) {
                log.warn("跳过重复题目: questionId={}, reason={}", 
                    selection.getQuestionId(), selection.getReason());
                continue;
            }
            
            AutoExamQuestion examQuestion = new AutoExamQuestion();
            examQuestion.setExamId(examId);
            examQuestion.setQuestionBankId(selection.getQuestionId());
            examQuestion.setQuestionOrder(order++);
            // 难度优先使用题库自身难度，其次使用AI返回的难度
            Integer difficulty = selection.getDifficulty();
            if (difficulty == null) {
                QuestionBank qb = questionBankMapper.selectById(selection.getQuestionId());
                difficulty = mapDifficultyToInt(qb != null ? qb.getDifficultyLevel() : null);
            }
            examQuestion.setDifficultyLevel(difficulty);
            examQuestion.setEstimatedTimeMinutes(selection.getEstimatedTime());
            examQuestion.setAiSelectionReason(selection.getAiSelectionReason() != null ? 
                selection.getAiSelectionReason() : selection.getReason());
            examQuestion.setCreatedAt(LocalDateTime.now());
            
            // 如果有知识点信息，尝试获取知识点ID
            if (selection.getKnowledgePoint() != null) {
                Long knowledgePointId = getKnowledgePointIdByName(selection.getKnowledgePoint());
                examQuestion.setKnowledgePointId(knowledgePointId);
            }
            
            examQuestions.add(examQuestion);
            addedQuestionIds.add(selection.getQuestionId());
        }
        
        log.info("去重后实际保存题目数量: {}/{}", examQuestions.size(), questionSelections.size());
        autoExamQuestionMapper.insertBatch(examQuestions);
    }
    
    /**
     * 根据知识点名称获取知识点ID
     */
    private Long getKnowledgePointIdByName(String knowledgePointName) {
        try {
            // 由于KnowledgePointMapper没有selectOne方法，我们使用selectByCourseId然后过滤
            // 这里简化处理，直接返回null，在实际项目中应该添加相应的查询方法
            log.warn("知识点ID查找功能需要完善，当前返回null: " + knowledgePointName);
            return null;
        } catch (Exception e) {
            log.warn("获取知识点ID失败: " + knowledgePointName, e);
            return null;
        }
    }
    
    private void logGeneration(ExamGenerationRequest request, String aiResponse, ExamGenerationResult result, long generationTime) {
        // 记录生成日志
        // 实现日志记录逻辑
    }
    
    private ExamPreviewVO buildExamPreviewVO(AutoGeneratedExam exam, List<AutoExamQuestion> examQuestions) {
        log.info("开始构建试卷预览VO: examId={}, examQuestions.size()={}", exam.getId(), examQuestions.size());
        
        // 构建试卷预览VO
        ExamPreviewVO preview = new ExamPreviewVO();
        preview.setExamId(exam.getId());
        preview.setExamTitle(exam.getExamTitle());
        preview.setExamDescription(exam.getExamDescription());
        preview.setTotalQuestions(examQuestions.size());
        preview.setTimeLimitMinutes(120); // 从配置中获取
        preview.setQualityScore(exam.getQualityScore());
        preview.setStatus(exam.getStatus());
        preview.setCreatedAt(exam.getCreatedAt());
        
        // 构建题目预览列表
        List<ExamPreviewVO.QuestionPreviewVO> questionPreviews = new ArrayList<>();
        for (AutoExamQuestion examQuestion : examQuestions) {
            log.info("处理试卷题目: examQuestionId={}, questionBankId={}", examQuestion.getId(), examQuestion.getQuestionBankId());
            
            QuestionBank question = questionBankMapper.selectById(examQuestion.getQuestionBankId());
            if (question != null) {
                log.info("找到题目详情: questionId={}, type={}, content={}", 
                    question.getId(), question.getType(), question.getContent().substring(0, Math.min(50, question.getContent().length())));
                
                ExamPreviewVO.QuestionPreviewVO questionPreview = new ExamPreviewVO.QuestionPreviewVO();
                questionPreview.setQuestionId(question.getId());
                questionPreview.setType(question.getType());
                questionPreview.setContent(question.getContent());
                questionPreview.setAnswer(question.getAnswer());
                questionPreview.setKnowledgePoint(question.getKnowledgePoint());
                questionPreview.setDifficultyLevel(examQuestion.getDifficultyLevel());
                questionPreview.setEstimatedTimeMinutes(examQuestion.getEstimatedTimeMinutes());
                questionPreview.setAiSelectionReason(examQuestion.getAiSelectionReason());
                questionPreview.setQuestionOrder(examQuestion.getQuestionOrder());
                questionPreviews.add(questionPreview);
            } else {
                log.warn("未找到题目详情: questionBankId={}", examQuestion.getQuestionBankId());
            }
        }
        preview.setQuestions(questionPreviews);
        
        log.info("构建试卷预览VO完成: examId={}, questionPreviews.size()={}", exam.getId(), questionPreviews.size());
        
        return preview;
    }
    
    private String buildCurrentQuestionsJson(List<AutoExamQuestion> currentQuestions) {
        // 构建当前题目JSON
        return currentQuestions.stream()
                .map(q -> String.format("{\"id\":%d,\"order\":%d,\"difficulty\":%d}", 
                    q.getQuestionBankId(), q.getQuestionOrder(), q.getDifficultyLevel()))
                .collect(Collectors.joining(","));
    }
    
    private String buildAvailableQuestionsJson(List<QuestionBank> availableQuestions) {
        // 构建可选题目JSON
        return availableQuestions.stream()
                .map(q -> String.format("{\"id\":%d,\"type\":\"%s\",\"content\":\"%s\",\"difficulty\":%d}", 
                    q.getId(), q.getType(), q.getContent(), mapDifficultyToInt(q.getDifficultyLevel())))
                .collect(Collectors.joining(","));
    }

    /** 将题库难度字符串映射为整型：easy=1, medium=2, hard=3（默认2） */
    private int mapDifficultyToInt(String difficultyLevel) {
        String norm = getNormalizedDifficultyLevel(difficultyLevel);
        switch (norm) {
            case "easy": return 1;
            case "hard": return 3;
            default: return 2;
        }
    }

    /** 规范化难度字符串，兼容中文与别名 */
    private String getNormalizedDifficultyLevel(String level) {
        if (level == null) return "medium";
        String val = level.trim().toLowerCase();
        if ("简单".equals(level) || "易".equals(level) || "容易".equals(level) || "1".equals(val)) return "easy";
        if ("中等".equals(level) || "中".equals(level) || "2".equals(val)) return "medium";
        if ("困难".equals(level) || "难".equals(level) || "3".equals(val)) return "hard";
        if (val.contains("easy")) return "easy";
        if (val.contains("hard")) return "hard";
        if (val.contains("medium")) return "medium";
        return "medium";
    }

    /**
     * 根据难度分布从可用题目中抽样，返回题目ID列表。
     */
    private List<Long> enforceDifficultySampling(List<QuestionBank> pool, int total,
                                                 Map<String, Double> difficultyDistribution) {
        if (pool == null || pool.isEmpty()) return Collections.emptyList();
        Map<String, List<QuestionBank>> byDiff = pool.stream()
                .collect(Collectors.groupingBy(q -> getNormalizedDifficultyLevel(q.getDifficultyLevel())));

        Map<String, Double> dist = normalizeDifficultyDistribution(difficultyDistribution);
        int easyTarget = (int) Math.round(total * dist.getOrDefault("easy", 0.0));
        int medTarget  = (int) Math.round(total * dist.getOrDefault("medium", 0.0));
        int hardTarget = (int) Math.round(total * dist.getOrDefault("hard", 0.0));

        log.info("难度分布抽样目标: total={}, easy={}, medium={}, hard={} | pool: easy={}, medium={}, hard={}",
                total, easyTarget, medTarget, hardTarget,
                byDiff.getOrDefault("easy", Collections.emptyList()).size(),
                byDiff.getOrDefault("medium", Collections.emptyList()).size(),
                byDiff.getOrDefault("hard", Collections.emptyList()).size());

        List<Long> result = new ArrayList<>();
        pickRandom(byDiff.get("easy"), easyTarget, result);
        pickRandom(byDiff.get("medium"), medTarget, result);
        pickRandom(byDiff.get("hard"), hardTarget, result);

        // 若不足总数，用其它难度补足
        if (result.size() < total) {
            List<QuestionBank> remaining = new ArrayList<>(pool);
            // 去重
            remaining.removeIf(q -> result.contains(q.getId()));
            Collections.shuffle(remaining);
            for (QuestionBank q : remaining) {
                if (result.size() >= total) break;
                result.add(q.getId());
            }
        }
        return result;
    }

    private void pickRandom(List<QuestionBank> list, int target, List<Long> out) {
        if (target <= 0 || list == null || list.isEmpty()) return;
        List<QuestionBank> copy = new ArrayList<>(list);
        Collections.shuffle(copy);
        // 按目标数量截取
        int need = Math.min(target, copy.size());
        int added = 0;
        for (QuestionBank qb : copy) {
            if (added >= need) break;
            if (!out.contains(qb.getId())) { out.add(qb.getId()); added++; }
        }
    }

    /**
     * 校正AI返回的题目集合的难度分布；若偏差过大，则按目标分布重采样。
     */
    private List<QuestionSelection> validateAndRebalanceSelection(List<QuestionBank> pool,
                                                                  List<QuestionSelection> aiSel,
                                                                  int total,
                                                                  Map<String, Double> targetDist) {
        if (aiSel == null || aiSel.isEmpty()) return null;
        Map<String, Long> count = new HashMap<>();
        for (QuestionSelection s : aiSel) {
            QuestionBank qb = pool.stream().filter(q -> Objects.equals(q.getId(), s.getQuestionId())).findFirst().orElse(null);
            String d = getNormalizedDifficultyLevel(qb != null ? qb.getDifficultyLevel() : null);
            count.merge(d, 1L, Long::sum);
        }
        double easyRate = count.getOrDefault("easy", 0L) * 1.0 / aiSel.size();
        double medRate  = count.getOrDefault("medium", 0L) * 1.0 / aiSel.size();
        double hardRate = count.getOrDefault("hard", 0L) * 1.0 / aiSel.size();
        log.info("AI返回难度比例: easy={}, medium={}, hard={} | 目标: {}", easyRate, medRate, hardRate, targetDist);

        // 偏差阈值：任一难度偏离目标超过30%则认为需要重平衡
        boolean needRebalance = Math.abs(easyRate - targetDist.getOrDefault("easy", 0.0)) > 0.3
                || Math.abs(medRate - targetDist.getOrDefault("medium", 0.0)) > 0.3
                || Math.abs(hardRate - targetDist.getOrDefault("hard", 0.0)) > 0.3;
        if (!needRebalance) return null;

        List<Long> ids = enforceDifficultySampling(pool, total, targetDist);
        List<QuestionSelection> fixed = ids.stream().map(id -> {
            QuestionBank qb = pool.stream().filter(q -> Objects.equals(q.getId(), id)).findFirst().orElse(null);
            QuestionSelection s = new QuestionSelection();
            s.setQuestionId(id);
            s.setDifficulty(mapDifficultyToInt(qb != null ? qb.getDifficultyLevel() : null));
            s.setEstimatedTime(qb != null && qb.getEstimatedTimeMinutes()!=null ? qb.getEstimatedTimeMinutes() : 5);
            s.setKnowledgePoint(qb != null ? qb.getKnowledgePoint() : null);
            s.setReason("重平衡难度占比");
            return s;
        }).collect(Collectors.toList());
        return fixed;
    }

    /** 规范化来自前端的难度分布，兼容中文键与百分比 */
    private Map<String, Double> normalizeDifficultyDistribution(Map<String, Double> raw) {
        Map<String, Double> dist = new HashMap<>();
        if (raw != null) {
            for (Map.Entry<String, Double> e : raw.entrySet()) {
                String key = e.getKey();
                Double v = Optional.ofNullable(e.getValue()).orElse(0.0);
                String normKey;
                if ("简单".equals(key) || "易".equals(key) || "easy".equalsIgnoreCase(key)) normKey = "easy";
                else if ("中等".equals(key) || "中".equals(key) || "medium".equalsIgnoreCase(key)) normKey = "medium";
                else if ("困难".equals(key) || "难".equals(key) || "hard".equalsIgnoreCase(key)) normKey = "hard";
                else normKey = key.toLowerCase();
                dist.merge(normKey, v, Double::sum);
            }
        }
        // 如果像百分比一样 > 1，则按100缩放
        double sum = dist.values().stream().mapToDouble(d -> d).sum();
        if (sum > 1.01) {
            dist.replaceAll((k, v) -> v / 100.0);
            sum = dist.values().stream().mapToDouble(d -> d).sum();
        }
        // 归一化到和为1
        if (sum == 0) {
            dist.put("medium", 1.0);
        } else {
            final double total = sum;
            dist.replaceAll((k, v) -> v / total);
        }
        // 确保三个键都存在
        dist.putIfAbsent("easy", 0.0);
        dist.putIfAbsent("medium", 0.0);
        dist.putIfAbsent("hard", 0.0);
        return dist;
    }
    
    private ExamAdjustmentResult parseAdjustmentResponse(String aiResponse) {
        // 解析调整响应
        try {
            return objectMapper.readValue(aiResponse, ExamAdjustmentResult.class);
        } catch (Exception e) {
            log.error("解析调整响应失败", e);
            throw new RuntimeException("解析调整响应失败", e);
        }
    }
    
    private void applyAdjustment(Long examId, ExamAdjustmentResult adjustmentResult) {
        // 简化实现：支持三种操作 remove/replace/add
        if (adjustmentResult == null || adjustmentResult.getQuestionChanges() == null) return;
        for (QuestionChange change : adjustmentResult.getQuestionChanges()) {
            String action = change.getAction();
            if ("remove".equalsIgnoreCase(action)) {
                // 删除指定题目
                if (change.getQuestionId() != null) {
                    autoExamQuestionMapper.deleteByExamAndQuestion(examId, change.getQuestionId());
                }
            } else if ("replace".equalsIgnoreCase(action)) {
                // 用同难度/同知识点的其它题替换（此处简单实现：先删后补任意一题）
                if (change.getQuestionId() != null) {
                    autoExamQuestionMapper.deleteByExamAndQuestion(examId, change.getQuestionId());
                }
                // 补一题：从题库中任选一题加入
                List<QuestionBank> pool = questionBankMapper.selectByCourseId(null);
                if (pool != null && !pool.isEmpty()) {
                    QuestionBank qb = pool.get(0);
                    AutoExamQuestion q = new AutoExamQuestion();
                    q.setExamId(examId);
                    q.setQuestionBankId(qb.getId());
                    q.setQuestionOrder(9999); // 暂定，后续重排
                    q.setDifficultyLevel(mapDifficultyToInt(qb.getDifficultyLevel()));
                    q.setEstimatedTimeMinutes(qb.getEstimatedTimeMinutes());
                    q.setCreatedAt(LocalDateTime.now());
                    autoExamQuestionMapper.insert(q);
                }
            } else if ("add".equalsIgnoreCase(action)) {
                // 添加一题（基于需求简单从题库挑一题加入）
                List<QuestionBank> pool = questionBankMapper.selectList(new QueryWrapper<>());
                if (pool != null && !pool.isEmpty()) {
                    QuestionBank qb = pool.get(0);
                    AutoExamQuestion q = new AutoExamQuestion();
                    q.setExamId(examId);
                    q.setQuestionBankId(qb.getId());
                    q.setQuestionOrder(9999);
                    q.setDifficultyLevel(mapDifficultyToInt(qb.getDifficultyLevel()));
                    q.setEstimatedTimeMinutes(qb.getEstimatedTimeMinutes());
                    q.setCreatedAt(LocalDateTime.now());
                    autoExamQuestionMapper.insert(q);
                }
            }
        }
        // 重新排序
        reorderExamQuestions(examId);
    }

    private void reorderExamQuestions(Long examId) {
        List<AutoExamQuestion> list = autoExamQuestionMapper.selectByExamId(examId);
        int order = 1;
        for (AutoExamQuestion eq : list) {
            autoExamQuestionMapper.updateQuestionOrder(eq.getId(), order++);
        }
    }

    private Long extractQuestionId(String requirements) {
        if (requirements == null || requirements.isEmpty()) return null;
        try {
            Map<?,?> m = objectMapper.readValue(requirements, Map.class);
            Object v = m.get("questionId");
            if (v instanceof Number) return ((Number) v).longValue();
            if (v != null) return Long.parseLong(String.valueOf(v));
            return null;
        } catch (Exception ignore) {
            return null;
        }
    }
    
    // 内部类
    private static class QuestionBankStats {
        private int choiceCount = 0;
        private int shortAnswerCount = 0;
        private int programmingCount = 0;
        
        public int getChoiceCount() { return choiceCount; }
        public int getShortAnswerCount() { return shortAnswerCount; }
        public int getProgrammingCount() { return programmingCount; }
    }
    
    private static class KnowledgePointCoverage {
        private List<String> coveredPoints;
        private Double coverageRate;
        
        // getters and setters
        public List<String> getCoveredPoints() { return coveredPoints; }
        public void setCoveredPoints(List<String> coveredPoints) { this.coveredPoints = coveredPoints; }
        public Double getCoverageRate() { return coverageRate; }
        public void setCoverageRate(Double coverageRate) { this.coverageRate = coverageRate; }
    }
    
    private static class ExamGenerationResult {
        private String strategy;
        private List<QuestionSelection> questionSelection;
        private KnowledgePointCoverage knowledgePointCoverage;
        private QualityAssessment qualityAssessment;
        private Object suggestions;
        
        // getters and setters
        public String getStrategy() { return strategy; }
        public void setStrategy(String strategy) { this.strategy = strategy; }
        public List<QuestionSelection> getQuestionSelection() { return questionSelection; }
        public void setQuestionSelection(List<QuestionSelection> questionSelection) { this.questionSelection = questionSelection; }
        public KnowledgePointCoverage getKnowledgePointCoverage() { return knowledgePointCoverage; }
        public void setKnowledgePointCoverage(KnowledgePointCoverage knowledgePointCoverage) { this.knowledgePointCoverage = knowledgePointCoverage; }
        public QualityAssessment getQualityAssessment() { return qualityAssessment; }
        public void setQualityAssessment(QualityAssessment qualityAssessment) { this.qualityAssessment = qualityAssessment; }
        public Object getSuggestions() { return suggestions; }
        public void setSuggestions(Object suggestions) { this.suggestions = suggestions; }
    }
    
    
    private static class QualityAssessment {
        private Double overallScore;
        private Double difficultyBalance;
        private Double knowledgeCoverage;
        private Double timeDistribution;
        
        // getters and setters
        public Double getOverallScore() { return overallScore; }
        public void setOverallScore(Double overallScore) { this.overallScore = overallScore; }
        public Double getDifficultyBalance() { return difficultyBalance; }
        public void setDifficultyBalance(Double difficultyBalance) { this.difficultyBalance = difficultyBalance; }
        public Double getKnowledgeCoverage() { return knowledgeCoverage; }
        public void setKnowledgeCoverage(Double knowledgeCoverage) { this.knowledgeCoverage = knowledgeCoverage; }
        public Double getTimeDistribution() { return timeDistribution; }
        public void setTimeDistribution(Double timeDistribution) { this.timeDistribution = timeDistribution; }
    }
    
    private static class ExamAdjustmentResult {
        private String adjustmentStrategy;
        private List<QuestionChange> questionChanges;
        private String qualityImpact;
        private String suggestions;
        
        // getters and setters
        public String getAdjustmentStrategy() { return adjustmentStrategy; }
        public void setAdjustmentStrategy(String adjustmentStrategy) { this.adjustmentStrategy = adjustmentStrategy; }
        public List<QuestionChange> getQuestionChanges() { return questionChanges; }
        public void setQuestionChanges(List<QuestionChange> questionChanges) { this.questionChanges = questionChanges; }
        public String getQualityImpact() { return qualityImpact; }
        public void setQualityImpact(String qualityImpact) { this.qualityImpact = qualityImpact; }
        public String getSuggestions() { return suggestions; }
        public void setSuggestions(String suggestions) { this.suggestions = suggestions; }
    }
    
    private static class QuestionChange {
        private String action;
        private Long questionId;
        private String reason;
        private Integer newOrder;
        
        // getters and setters
        public String getAction() { return action; }
        public void setAction(String action) { this.action = action; }
        public Long getQuestionId() { return questionId; }
        public void setQuestionId(Long questionId) { this.questionId = questionId; }
        public String getReason() { return reason; }
        public void setReason(String reason) { this.reason = reason; }
        public Integer getNewOrder() { return newOrder; }
        public void setNewOrder(Integer newOrder) { this.newOrder = newOrder; }
    }
    
    /**
     * 根据知识点和题库分类从题库中筛选题目
     */
    private List<QuestionBank> getQuestionsByKnowledgePoints(Long courseId, List<String> selectedKnowledgePoints, Long categoryId) {
        // 先检查数据库中是否有题目
        List<QuestionBank> allQuestions = questionBankMapper.selectList(new QueryWrapper<>());
        log.info("数据库中总题目数量: {}", allQuestions.size());
        
        if (allQuestions.isEmpty()) {
            log.warn("数据库中没有任何题目！");
            return allQuestions;
        }
        
        // 打印前几条题目信息用于调试
        log.info("数据库中的前3条题目:");
        allQuestions.stream().limit(3).forEach(q -> {
            log.info("题目ID: {}, 课程ID: {}, 分类ID: {}, 类型: {}, 知识点: {}, 内容: {}", 
                    q.getId(), q.getCourseId(), q.getCategoryId(), q.getType(), q.getKnowledgePoint(), 
                    q.getContent() != null && q.getContent().length() > 50 ? q.getContent().substring(0, 50) + "..." : q.getContent());
        });
        
        QueryWrapper<QuestionBank> queryWrapper = new QueryWrapper<>();
        queryWrapper.eq("course_id", courseId);
        
        // 如果指定了题库分类，添加分类筛选条件
        if (categoryId != null) {
            queryWrapper.eq("category_id", categoryId);
        }
        
        // 如果选择了知识点，添加知识点筛选条件
        if (selectedKnowledgePoints != null && !selectedKnowledgePoints.isEmpty()) {
        // 使用OR条件匹配任意一个选中的知识点
        queryWrapper.and(wrapper -> {
            for (String knowledgePoint : selectedKnowledgePoints) {
                wrapper.like("knowledge_point", knowledgePoint).or();
            }
        });
        }
        
        List<QuestionBank> questions = questionBankMapper.selectList(queryWrapper);
        log.info("筛选到的题目数量: {}, 课程ID: {}, 分类ID: {}, 知识点: {}", 
                questions.size(), courseId, categoryId, selectedKnowledgePoints);
        
        // 打印筛选后的题目信息用于调试
        if (!questions.isEmpty()) {
            log.info("筛选后的前3条题目信息:");
            questions.stream().limit(3).forEach(q -> {
                log.info("题目ID: {}, 类型: {}, 知识点: {}, 内容: {}", 
                        q.getId(), q.getType(), q.getKnowledgePoint(), 
                        q.getContent().length() > 50 ? q.getContent().substring(0, 50) + "..." : q.getContent());
            });
        } else {
            log.warn("没有找到符合条件的题目！");
            // 尝试不按知识点筛选
            QueryWrapper<QuestionBank> fallbackWrapper = new QueryWrapper<>();
            fallbackWrapper.eq("course_id", courseId);
            if (categoryId != null) {
                fallbackWrapper.eq("category_id", categoryId);
            }
            List<QuestionBank> fallbackQuestions = questionBankMapper.selectList(fallbackWrapper);
            log.info("不按知识点筛选的题目数量: {}", fallbackQuestions.size());
        }
        
        return questions;
    }
    
    /**
     * 构建题库JSON数据供AI使用
     */
    private String buildQuestionBankJson(List<QuestionBank> questions) {
        try {
            List<Map<String, Object>> questionList = questions.stream().map(q -> {
                Map<String, Object> questionMap = new HashMap<>();
                questionMap.put("id", q.getId());
                questionMap.put("type", q.getType());
                questionMap.put("content", q.getContent());
                questionMap.put("answer", q.getAnswer());
                questionMap.put("knowledgePoint", q.getKnowledgePoint());
                questionMap.put("difficultyLevel", q.getDifficultyLevel());
                questionMap.put("categoryId", q.getCategoryId());
                questionMap.put("estimatedTimeMinutes", q.getEstimatedTimeMinutes());
                questionMap.put("tags", q.getTags());
                questionMap.put("isAiGenerated", q.getIsAiGenerated());
                questionMap.put("qualityScore", q.getQualityScore());
                questionMap.put("createdBy", q.getCreatedBy());
                // 将LocalDateTime转换为字符串
                questionMap.put("createdAt", q.getCreatedAt() != null ? q.getCreatedAt().toString() : null);
                return questionMap;
            }).collect(Collectors.toList());
            
            Map<String, Object> result = new HashMap<>();
            result.put("totalQuestions", questions.size());
            result.put("questions", questionList);
            
            // 按题型分组统计
            Map<String, Long> typeCount = questions.stream()
                .collect(Collectors.groupingBy(QuestionBank::getType, Collectors.counting()));
            result.put("typeDistribution", typeCount);
            
            // 按知识点分组统计
            Map<String, Long> knowledgeCount = questions.stream()
                .collect(Collectors.groupingBy(QuestionBank::getKnowledgePoint, Collectors.counting()));
            result.put("knowledgeDistribution", knowledgeCount);
            
            // 按难度分组统计
            Map<String, Long> difficultyCount = questions.stream()
                .collect(Collectors.groupingBy(QuestionBank::getDifficultyLevel, Collectors.counting()));
            result.put("difficultyDistribution", difficultyCount);
            
            return objectMapper.writeValueAsString(result);
        } catch (Exception e) {
            log.error("构建题库JSON失败", e);
            return "{}";
        }
    }
}
